export interface University {
  id: string
  name: string
  country: string
  city: string
  ranking: number
  logo: string
  website: string
  languages: string[]
  tuitionFee: {
    min: number
    max: number
    currency: string
  }
  requirements: {
    ielts?: number
    toefl?: number
    sat?: number
    act?: number
    gpa: number
  }
  programs: string[]
  competitiveness: number // 1-10 scale
  acceptanceRate: number
  description: string
  establishedYear: number
  studentCount: number
  internationalStudents: number
}

export const universities: University[] = [
  {
    id: "mit",
    name: "Massachusetts Institute of Technology",
    country: "США",
    city: "Кембридж",
    ranking: 1,
    logo: "/mit-logo-generic.png",
    website: "https://web.mit.edu",
    languages: ["Английский"],
    tuitionFee: { min: 57986, max: 57986, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 90, sat: 1520, act: 34, gpa: 4.17 },
    programs: ["Инженерия", "Компьютерные науки", "Физика", "Математика", "Экономика"],
    competitiveness: 10,
    acceptanceRate: 4.1,
    description: "Ведущий технологический университет мира",
    establishedYear: 1861,
    studentCount: 11934,
    internationalStudents: 3748,
  },
  {
    id: "stanford",
    name: "Stanford University",
    country: "США",
    city: "Стэнфорд",
    ranking: 2,
    logo: "/stanford-seal.png",
    website: "https://www.stanford.edu",
    languages: ["Английский"],
    tuitionFee: { min: 56169, max: 56169, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 89, sat: 1505, act: 33, gpa: 4.18 },
    programs: ["Инженерия", "Бизнес", "Медицина", "Право", "Компьютерные науки"],
    competitiveness: 10,
    acceptanceRate: 3.9,
    description: "Престижный исследовательский университет в Силиконовой долине",
    establishedYear: 1885,
    studentCount: 17249,
    internationalStudents: 3879,
  },
  {
    id: "harvard",
    name: "Harvard University",
    country: "США",
    city: "Кембридж",
    ranking: 3,
    logo: "/harvard-seal.png",
    website: "https://www.harvard.edu",
    languages: ["Английский"],
    tuitionFee: { min: 54269, max: 54269, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 80, sat: 1515, act: 34, gpa: 4.2 },
    programs: ["Право", "Медицина", "Бизнес", "Искусство", "Науки"],
    competitiveness: 10,
    acceptanceRate: 3.4,
    description: "Старейший университет США с мировой репутацией",
    establishedYear: 1636,
    studentCount: 23731,
    internationalStudents: 5877,
  },
  {
    id: "caltech",
    name: "California Institute of Technology",
    country: "США",
    city: "Пасадена",
    ranking: 4,
    logo: "/caltech-logo.png",
    website: "https://www.caltech.edu",
    languages: ["Английский"],
    tuitionFee: { min: 58680, max: 58680, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 90, sat: 1560, act: 35, gpa: 4.19 },
    programs: ["Инженерия", "Физика", "Химия", "Биология", "Математика"],
    competitiveness: 10,
    acceptanceRate: 2.7,
    description: "Элитный технологический институт",
    establishedYear: 1891,
    studentCount: 2397,
    internationalStudents: 688,
  },
  {
    id: "oxford",
    name: "University of Oxford",
    country: "Великобритания",
    city: "Оксфорд",
    ranking: 5,
    logo: "/placeholder-mkw7j.png",
    website: "https://www.ox.ac.uk",
    languages: ["Английский"],
    tuitionFee: { min: 28370, max: 44240, currency: "GBP" },
    requirements: { ielts: 7.0, toefl: 100, gpa: 3.7 },
    programs: ["Гуманитарные науки", "Медицина", "Право", "Естественные науки", "Социальные науки"],
    competitiveness: 9,
    acceptanceRate: 13.1,
    description: "Старейший англоязычный университет мира",
    establishedYear: 1096,
    studentCount: 24515,
    internationalStudents: 12010,
  },
  {
    id: "cambridge",
    name: "University of Cambridge",
    country: "Великобритания",
    city: "Кембридж",
    ranking: 6,
    logo: "/cambridge-crest.png",
    website: "https://www.cam.ac.uk",
    languages: ["Английский"],
    tuitionFee: { min: 24507, max: 58038, currency: "GBP" },
    requirements: { ielts: 7.5, toefl: 110, gpa: 3.7 },
    programs: ["Математика", "Естественные науки", "Инженерия", "Медицина", "Гуманитарные науки"],
    competitiveness: 9,
    acceptanceRate: 18.8,
    description: "Престижный исследовательский университет с богатой историей",
    establishedYear: 1209,
    studentCount: 24450,
    internationalStudents: 9327,
  },
  {
    id: "eth-zurich",
    name: "ETH Zurich",
    country: "Швейцария",
    city: "Цюрих",
    ranking: 7,
    logo: "/eth-zurich-logo.png",
    website: "https://ethz.ch",
    languages: ["Немецкий", "Английский"],
    tuitionFee: { min: 1298, max: 1298, currency: "CHF" },
    requirements: { ielts: 7.0, toefl: 100, gpa: 3.5 },
    programs: ["Инженерия", "Естественные науки", "Математика", "Архитектура", "Информатика"],
    competitiveness: 8,
    acceptanceRate: 27.0,
    description: "Ведущий технический университет Европы",
    establishedYear: 1855,
    studentCount: 22200,
    internationalStudents: 8880,
  },
  {
    id: "ucl",
    name: "University College London",
    country: "Великобритания",
    city: "Лондон",
    ranking: 8,
    logo: "/generic-university-logo.png",
    website: "https://www.ucl.ac.uk",
    languages: ["Английский"],
    tuitionFee: { min: 25800, max: 48500, currency: "GBP" },
    requirements: { ielts: 6.5, toefl: 92, gpa: 3.3 },
    programs: ["Медицина", "Инженерия", "Искусство", "Социальные науки", "Право"],
    competitiveness: 7,
    acceptanceRate: 48.0,
    description: "Многопрофильный исследовательский университет в центре Лондона",
    establishedYear: 1826,
    studentCount: 43840,
    internationalStudents: 24145,
  },
  {
    id: "imperial",
    name: "Imperial College London",
    country: "Великобритания",
    city: "Лондон",
    ranking: 9,
    logo: "/imperial-college-logo.png",
    website: "https://www.imperial.ac.uk",
    languages: ["Английский"],
    tuitionFee: { min: 35100, max: 50400, currency: "GBP" },
    requirements: { ielts: 7.0, toefl: 100, gpa: 3.7 },
    programs: ["Инженерия", "Медицина", "Естественные науки", "Бизнес"],
    competitiveness: 8,
    acceptanceRate: 14.3,
    description: "Специализируется на науке, технологиях, инженерии и медицине",
    establishedYear: 1907,
    studentCount: 19945,
    internationalStudents: 11945,
  },
  {
    id: "chicago",
    name: "University of Chicago",
    country: "США",
    city: "Чикаго",
    ranking: 10,
    logo: "/university-of-chicago-logo.png",
    website: "https://www.uchicago.edu",
    languages: ["Английский"],
    tuitionFee: { min: 62940, max: 62940, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 104, sat: 1520, act: 34, gpa: 4.0 },
    programs: ["Экономика", "Бизнес", "Право", "Медицина", "Социальные науки"],
    competitiveness: 9,
    acceptanceRate: 5.4,
    description: "Известен сильными программами по экономике и социальным наукам",
    establishedYear: 1890,
    studentCount: 18452,
    internationalStudents: 4613,
  },
  {
    id: "princeton",
    name: "Princeton University",
    country: "США",
    city: "Принстон",
    ranking: 11,
    logo: "/princeton-tiger-logo.png",
    website: "https://www.princeton.edu",
    languages: ["Английский"],
    tuitionFee: { min: 57410, max: 57410, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 100, sat: 1510, act: 34, gpa: 3.95 },
    programs: ["Инженерия", "Естественные науки", "Гуманитарные науки", "Социальные науки", "Экономика"],
    competitiveness: 10,
    acceptanceRate: 4.0,
    description: "Престижный исследовательский университет Лиги плюща",
    establishedYear: 1746,
    studentCount: 5428,
    internationalStudents: 1356,
  },
  {
    id: "nus",
    name: "National University of Singapore",
    country: "Сингапур",
    city: "Сингапур",
    ranking: 12,
    logo: "/nus-singapore-logo.png",
    website: "https://www.nus.edu.sg",
    languages: ["Английский"],
    tuitionFee: { min: 17550, max: 39000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 85, sat: 1350, gpa: 3.6 },
    programs: ["Инженерия", "Бизнес", "Компьютерные науки", "Медицина", "Право"],
    competitiveness: 8,
    acceptanceRate: 5.0,
    description: "Ведущий университет Азии с мировым признанием",
    establishedYear: 1905,
    studentCount: 40000,
    internationalStudents: 12000,
  },
  {
    id: "peking",
    name: "Peking University",
    country: "Китай",
    city: "Пекин",
    ranking: 13,
    logo: "/peking-university-logo.png",
    website: "https://english.pku.edu.cn",
    languages: ["Китайский", "Английский"],
    tuitionFee: { min: 4600, max: 6000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 90, gpa: 3.5 },
    programs: ["Гуманитарные науки", "Естественные науки", "Социальные науки", "Медицина", "Инженерия"],
    competitiveness: 9,
    acceptanceRate: 0.1,
    description: "Старейший и престижнейший университет Китая",
    establishedYear: 1898,
    studentCount: 46000,
    internationalStudents: 8000,
  },
  {
    id: "upenn",
    name: "University of Pennsylvania",
    country: "США",
    city: "Филадельфия",
    ranking: 14,
    logo: "/university-of-pennsylvania-coat-of-arms.png",
    website: "https://www.upenn.edu",
    languages: ["Английский"],
    tuitionFee: { min: 63452, max: 63452, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 100, sat: 1510, act: 34, gpa: 3.9 },
    programs: ["Бизнес", "Инженерия", "Медицина", "Право", "Социальные науки"],
    competitiveness: 9,
    acceptanceRate: 5.9,
    description: "Университет Лиги плюща с сильной бизнес-школой",
    establishedYear: 1740,
    studentCount: 28201,
    internationalStudents: 5640,
  },
  {
    id: "tsinghua",
    name: "Tsinghua University",
    country: "Китай",
    city: "Пекин",
    ranking: 15,
    logo: "/tsinghua-university-logo.png",
    website: "https://www.tsinghua.edu.cn/en",
    languages: ["Китайский", "Английский"],
    tuitionFee: { min: 4500, max: 5800, currency: "USD" },
    requirements: { ielts: 6.0, toefl: 80, gpa: 3.4 },
    programs: ["Инженерия", "Компьютерные науки", "Естественные науки", "Экономика", "Архитектура"],
    competitiveness: 9,
    acceptanceRate: 0.2,
    description: "Ведущий технический университет Китая",
    establishedYear: 1911,
    studentCount: 53000,
    internationalStudents: 3000,
  },
  {
    id: "edinburgh",
    name: "University of Edinburgh",
    country: "Великобритания",
    city: "Эдинбург",
    ranking: 16,
    logo: "/university-of-edinburgh-crest.png",
    website: "https://www.ed.ac.uk",
    languages: ["Английский"],
    tuitionFee: { min: 24500, max: 34800, currency: "GBP" },
    requirements: { ielts: 6.5, toefl: 92, gpa: 3.3 },
    programs: ["Медицина", "Инженерия", "Гуманитарные науки", "Естественные науки", "Бизнес"],
    competitiveness: 7,
    acceptanceRate: 40.0,
    description: "Исторический университет с сильными исследовательскими программами",
    establishedYear: 1582,
    studentCount: 47000,
    internationalStudents: 19000,
  },
  {
    id: "kcl",
    name: "King's College London",
    country: "Великобритания",
    city: "Лондон",
    ranking: 17,
    logo: "/kings-college-london-logo.png",
    website: "https://www.kcl.ac.uk",
    languages: ["Английский"],
    tuitionFee: { min: 28050, max: 46650, currency: "GBP" },
    requirements: { ielts: 6.5, toefl: 92, gpa: 3.3 },
    programs: ["Медицина", "Право", "Гуманитарные науки", "Социальные науки", "Естественные науки"],
    competitiveness: 7,
    acceptanceRate: 13.0,
    description: "Престижный исследовательский университет в центре Лондона",
    establishedYear: 1829,
    studentCount: 41000,
    internationalStudents: 17000,
  },
  {
    id: "lse",
    name: "London School of Economics",
    country: "Великобритания",
    city: "Лондон",
    ranking: 18,
    logo: "/lse-logo.png",
    website: "https://www.lse.ac.uk",
    languages: ["Английский"],
    tuitionFee: { min: 25608, max: 25608, currency: "GBP" },
    requirements: { ielts: 7.0, toefl: 100, gpa: 3.7 },
    programs: ["Экономика", "Политические науки", "Социология", "Право", "Международные отношения"],
    competitiveness: 8,
    acceptanceRate: 8.9,
    description: "Специализируется на социальных науках и экономике",
    establishedYear: 1895,
    studentCount: 12330,
    internationalStudents: 8200,
  },
  {
    id: "tokyo",
    name: "University of Tokyo",
    country: "Япония",
    city: "Токио",
    ranking: 19,
    logo: "/university-of-tokyo-logo.png",
    website: "https://www.u-tokyo.ac.jp/en",
    languages: ["Японский", "Английский"],
    tuitionFee: { min: 3360, max: 3360, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 88, gpa: 3.5 },
    programs: ["Инженерия", "Естественные науки", "Медицина", "Гуманитарные науки", "Экономика"],
    competitiveness: 9,
    acceptanceRate: 3.0,
    description: "Ведущий университет Японии с мировой репутацией",
    establishedYear: 1877,
    studentCount: 28000,
    internationalStudents: 4000,
  },
  {
    id: "melbourne",
    name: "University of Melbourne",
    country: "Австралия",
    city: "Мельбурн",
    ranking: 20,
    logo: "/university-of-melbourne-coat-of-arms.png",
    website: "https://www.unimelb.edu.au",
    languages: ["Английский"],
    tuitionFee: { min: 32000, max: 48000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 79, gpa: 3.0 },
    programs: ["Медицина", "Инженерия", "Бизнес", "Право", "Искусство"],
    competitiveness: 6,
    acceptanceRate: 70.0,
    description: "Ведущий университет Австралии с сильными исследовательскими программами",
    establishedYear: 1853,
    studentCount: 51000,
    internationalStudents: 21000,
  },
  {
    id: "yale",
    name: "Yale University",
    country: "США",
    city: "Нью-Хейвен",
    ranking: 21,
    logo: "/placeholder-ujr47.png",
    website: "https://www.yale.edu",
    languages: ["Английский"],
    tuitionFee: { min: 62250, max: 62250, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 100, sat: 1515, act: 34, gpa: 4.14 },
    programs: ["Право", "Медицина", "Искусство", "Гуманитарные науки", "Естественные науки"],
    competitiveness: 10,
    acceptanceRate: 4.6,
    description: "Престижный университет Лиги плюща",
    establishedYear: 1701,
    studentCount: 13433,
    internationalStudents: 2694,
  },
  {
    id: "columbia",
    name: "Columbia University",
    country: "США",
    city: "Нью-Йорк",
    ranking: 22,
    logo: "/placeholder-ujr47.png",
    website: "https://www.columbia.edu",
    languages: ["Английский"],
    tuitionFee: { min: 65524, max: 65524, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 100, sat: 1510, act: 34, gpa: 4.15 },
    programs: ["Журналистика", "Бизнес", "Медицина", "Право", "Инженерия"],
    competitiveness: 10,
    acceptanceRate: 3.9,
    description: "Университет Лиги плюща в сердце Нью-Йорка",
    establishedYear: 1754,
    studentCount: 33413,
    internationalStudents: 13347,
  },
  {
    id: "toronto",
    name: "University of Toronto",
    country: "Канада",
    city: "Торонто",
    ranking: 23,
    logo: "/placeholder-ujr47.png",
    website: "https://www.utoronto.ca",
    languages: ["Английский"],
    tuitionFee: { min: 58160, max: 58160, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 89, sat: 1510, act: 34, gpa: 3.6 },
    programs: ["Медицина", "Инженерия", "Бизнес", "Компьютерные науки", "Естественные науки"],
    competitiveness: 7,
    acceptanceRate: 43.0,
    description: "Ведущий исследовательский университет Канады",
    establishedYear: 1827,
    studentCount: 97000,
    internationalStudents: 25000,
  },
  {
    id: "cmu",
    name: "Carnegie Mellon University",
    country: "США",
    city: "Питтсбург",
    ranking: 24,
    logo: "/placeholder-ujr47.png",
    website: "https://www.cmu.edu",
    languages: ["Английский"],
    tuitionFee: { min: 61344, max: 61344, currency: "USD" },
    requirements: { ielts: 7.5, toefl: 102, sat: 1520, act: 34, gpa: 3.9 },
    programs: ["Компьютерные науки", "Инженерия", "Бизнес", "Искусство", "Дизайн"],
    competitiveness: 9,
    acceptanceRate: 11.3,
    description: "Ведущий университет в области компьютерных наук и технологий",
    establishedYear: 1900,
    studentCount: 15818,
    internationalStudents: 6327,
  },
  {
    id: "ucla",
    name: "University of California, Los Angeles",
    country: "США",
    city: "Лос-Анджелес",
    ranking: 25,
    logo: "/placeholder-ujr47.png",
    website: "https://www.ucla.edu",
    languages: ["Английский"],
    tuitionFee: { min: 46326, max: 46326, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 87, sat: 1405, act: 31, gpa: 4.0 },
    programs: ["Инженерия", "Медицина", "Бизнес", "Искусство", "Социальные науки"],
    competitiveness: 8,
    acceptanceRate: 8.6,
    description: "Престижный государственный исследовательский университет",
    establishedYear: 1919,
    studentCount: 47518,
    internationalStudents: 12000,
  },
  {
    id: "berkeley",
    name: "University of California, Berkeley",
    country: "США",
    city: "Беркли",
    ranking: 26,
    logo: "/placeholder-ujr47.png",
    website: "https://www.berkeley.edu",
    languages: ["Английский"],
    tuitionFee: { min: 46326, max: 46326, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 80, sat: 1415, act: 32, gpa: 3.9 },
    programs: ["Инженерия", "Компьютерные науки", "Бизнес", "Естественные науки", "Социальные науки"],
    competitiveness: 8,
    acceptanceRate: 11.4,
    description: "Флагманский кампус системы Калифорнийского университета",
    establishedYear: 1868,
    studentCount: 45057,
    internationalStudents: 10500,
  },
  {
    id: "manchester",
    name: "University of Manchester",
    country: "Великобритания",
    city: "Манчестер",
    ranking: 27,
    logo: "/placeholder-ujr47.png",
    website: "https://www.manchester.ac.uk",
    languages: ["Английский"],
    tuitionFee: { min: 26000, max: 47000, currency: "GBP" },
    requirements: { ielts: 6.0, toefl: 80, gpa: 3.2 },
    programs: ["Инженерия", "Медицина", "Бизнес", "Компьютерные науки", "Социальные науки"],
    competitiveness: 6,
    acceptanceRate: 56.0,
    description: "Крупный исследовательский университет с сильными программами",
    establishedYear: 1824,
    studentCount: 40000,
    internationalStudents: 12000,
  },
  {
    id: "anu",
    name: "Australian National University",
    country: "Австралия",
    city: "Канберра",
    ranking: 28,
    logo: "/placeholder-ujr47.png",
    website: "https://www.anu.edu.au",
    languages: ["Английский"],
    tuitionFee: { min: 35000, max: 50000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 80, gpa: 3.0 },
    programs: ["Политические науки", "Международные отношения", "Естественные науки", "Инженерия", "Экономика"],
    competitiveness: 7,
    acceptanceRate: 35.0,
    description: "Национальный университет Австралии с фокусом на исследования",
    establishedYear: 1946,
    studentCount: 25000,
    internationalStudents: 11000,
  },
  {
    id: "mcgill",
    name: "McGill University",
    country: "Канада",
    city: "Монреаль",
    ranking: 29,
    logo: "/placeholder-ujr47.png",
    website: "https://www.mcgill.ca",
    languages: ["Английский", "Французский"],
    tuitionFee: { min: 20000, max: 50000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 86, gpa: 3.7 },
    programs: ["Медицина", "Инженерия", "Бизнес", "Право", "Естественные науки"],
    competitiveness: 7,
    acceptanceRate: 46.0,
    description: "Престижный канадский университет с международной репутацией",
    establishedYear: 1821,
    studentCount: 40000,
    internationalStudents: 12000,
  },
  {
    id: "sydney",
    name: "University of Sydney",
    country: "Австралия",
    city: "Сидней",
    ranking: 30,
    logo: "/placeholder-ujr47.png",
    website: "https://www.sydney.edu.au",
    languages: ["Английский"],
    tuitionFee: { min: 30000, max: 55000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 85, gpa: 3.0 },
    programs: ["Медицина", "Инженерия", "Бизнес", "Право", "Архитектура"],
    competitiveness: 6,
    acceptanceRate: 30.0,
    description: "Старейший университет Австралии с красивым кампусом",
    establishedYear: 1850,
    studentCount: 73000,
    internationalStudents: 22000,
  },
  {
    id: "ntu",
    name: "Nanyang Technological University",
    country: "Сингапур",
    city: "Сингапур",
    ranking: 31,
    logo: "/placeholder-ujr47.png",
    website: "https://www.ntu.edu.sg",
    languages: ["Английский"],
    tuitionFee: { min: 18000, max: 40000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 90, sat: 1250, gpa: 3.5 },
    programs: ["Инженерия", "Бизнес", "Компьютерные науки", "Искусство", "Медицина"],
    competitiveness: 8,
    acceptanceRate: 25.0,
    description: "Молодой и быстро развивающийся технологический университет",
    establishedYear: 1991,
    studentCount: 33000,
    internationalStudents: 10000,
  },
  {
    id: "kaist",
    name: "Korea Advanced Institute of Science and Technology",
    country: "Южная Корея",
    city: "Тэджон",
    ranking: 32,
    logo: "/placeholder-ujr47.png",
    website: "https://www.kaist.ac.kr",
    languages: ["Корейский", "Английский"],
    tuitionFee: { min: 4000, max: 8000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 83, gpa: 3.5 },
    programs: ["Инженерия", "Компьютерные науки", "Естественные науки", "Бизнес"],
    competitiveness: 8,
    acceptanceRate: 20.0,
    description: "Ведущий технологический институт Южной Кореи",
    establishedYear: 1971,
    studentCount: 10000,
    internationalStudents: 1500,
  },
  {
    id: "hku",
    name: "University of Hong Kong",
    country: "Гонконг",
    city: "Гонконг",
    ranking: 33,
    logo: "/placeholder-ujr47.png",
    website: "https://www.hku.hk",
    languages: ["Английский", "Китайский"],
    tuitionFee: { min: 18000, max: 18000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 80, gpa: 3.4 },
    programs: ["Медицина", "Бизнес", "Право", "Инженерия", "Архитектура"],
    competitiveness: 7,
    acceptanceRate: 10.0,
    description: "Старейший университет Гонконга с международным признанием",
    establishedYear: 1911,
    studentCount: 29000,
    internationalStudents: 13000,
  },
  {
    id: "seoul",
    name: "Seoul National University",
    country: "Южная Корея",
    city: "Сеул",
    ranking: 34,
    logo: "/placeholder-ujr47.png",
    website: "https://www.snu.ac.kr",
    languages: ["Корейский", "Английский"],
    tuitionFee: { min: 3000, max: 6000, currency: "USD" },
    requirements: { ielts: 6.0, toefl: 80, gpa: 3.6 },
    programs: ["Медицина", "Инженерия", "Естественные науки", "Гуманитарные науки", "Социальные науки"],
    competitiveness: 9,
    acceptanceRate: 5.0,
    description: "Престижнейший университет Южной Кореи",
    establishedYear: 1946,
    studentCount: 28000,
    internationalStudents: 4000,
  },
  {
    id: "unsw",
    name: "University of New South Wales",
    country: "Австралия",
    city: "Сидней",
    ranking: 35,
    logo: "/placeholder-ujr47.png",
    website: "https://www.unsw.edu.au",
    languages: ["Английский"],
    tuitionFee: { min: 32000, max: 50000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 90, gpa: 3.0 },
    programs: ["Инженерия", "Бизнес", "Медицина", "Право", "Искусство"],
    competitiveness: 6,
    acceptanceRate: 58.0,
    description: "Инновационный университет с сильными связями с индустрией",
    establishedYear: 1949,
    studentCount: 65000,
    internationalStudents: 21000,
  },
  {
    id: "warwick",
    name: "University of Warwick",
    country: "Великобритания",
    city: "Ковентри",
    ranking: 36,
    logo: "/placeholder-ujr47.png",
    website: "https://warwick.ac.uk",
    languages: ["Английский"],
    tuitionFee: { min: 25770, max: 40710, currency: "GBP" },
    requirements: { ielts: 6.5, toefl: 87, gpa: 3.5 },
    programs: ["Бизнес", "Экономика", "Инженерия", "Компьютерные науки", "Математика"],
    competitiveness: 7,
    acceptanceRate: 12.9,
    description: "Молодой и амбициозный исследовательский университет",
    establishedYear: 1965,
    studentCount: 27000,
    internationalStudents: 12000,
  },
  {
    id: "bristol",
    name: "University of Bristol",
    country: "Великобритания",
    city: "Бристоль",
    ranking: 37,
    logo: "/placeholder-ujr47.png",
    website: "https://www.bristol.ac.uk",
    languages: ["Английский"],
    tuitionFee: { min: 24700, max: 27200, currency: "GBP" },
    requirements: { ielts: 6.5, toefl: 88, gpa: 3.4 },
    programs: ["Инженерия", "Медицина", "Естественные науки", "Социальные науки", "Искусство"],
    competitiveness: 7,
    acceptanceRate: 13.0,
    description: "Престижный исследовательский университет с сильной репутацией",
    establishedYear: 1876,
    studentCount: 27000,
    internationalStudents: 7000,
  },
  {
    id: "tu-delft",
    name: "Delft University of Technology",
    country: "Нидерланды",
    city: "Делфт",
    ranking: 38,
    logo: "/placeholder-ujr47.png",
    website: "https://www.tudelft.nl",
    languages: ["Нидерландский", "Английский"],
    tuitionFee: { min: 2314, max: 18750, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 90, gpa: 3.0 },
    programs: ["Инженерия", "Архитектура", "Компьютерные науки", "Естественные науки"],
    competitiveness: 7,
    acceptanceRate: 50.0,
    description: "Ведущий технический университет Нидерландов",
    establishedYear: 1842,
    studentCount: 26000,
    internationalStudents: 8000,
  },
  {
    id: "brown",
    name: "Brown University",
    country: "США",
    city: "Провиденс",
    ranking: 39,
    logo: "/placeholder-ujr47.png",
    website: "https://www.brown.edu",
    languages: ["Английский"],
    tuitionFee: { min: 62680, max: 62680, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 100, sat: 1505, act: 34, gpa: 4.1 },
    programs: ["Медицина", "Инженерия", "Компьютерные науки", "Искусство", "Социальные науки"],
    competitiveness: 9,
    acceptanceRate: 5.4,
    description: "Университет Лиги плюща с либеральной учебной программой",
    establishedYear: 1764,
    studentCount: 10696,
    internationalStudents: 2139,
  },
  {
    id: "northwestern",
    name: "Northwestern University",
    country: "США",
    city: "Эванстон",
    ranking: 40,
    logo: "/placeholder-ujr47.png",
    website: "https://www.northwestern.edu",
    languages: ["Английский"],
    tuitionFee: { min: 63468, max: 63468, currency: "USD" },
    requirements: { ielts: 7.5, toefl: 109, sat: 1520, act: 34, gpa: 4.1 },
    programs: ["Журналистика", "Инженерия", "Бизнес", "Медицина", "Искусство"],
    competitiveness: 9,
    acceptanceRate: 7.0,
    description: "Престижный частный исследовательский университет",
    establishedYear: 1851,
    studentCount: 22603,
    internationalStudents: 4521,
  },
  {
    id: "duke",
    name: "Duke University",
    country: "США",
    city: "Дарем",
    ranking: 41,
    logo: "/placeholder-ujr47.png",
    website: "https://www.duke.edu",
    languages: ["Английский"],
    tuitionFee: { min: 63054, max: 63054, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 100, sat: 1520, act: 34, gpa: 4.13 },
    programs: ["Медицина", "Инженерия", "Бизнес", "Право", "Политические науки"],
    competitiveness: 9,
    acceptanceRate: 6.2,
    description: "Элитный частный исследовательский университет",
    establishedYear: 1838,
    studentCount: 17198,
    internationalStudents: 1720,
  },
  {
    id: "vanderbilt",
    name: "Vanderbilt University",
    country: "США",
    city: "Нэшвилл",
    ranking: 42,
    logo: "/placeholder-ujr47.png",
    website: "https://www.vanderbilt.edu",
    languages: ["Английский"],
    tuitionFee: { min: 58130, max: 58130, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 100, sat: 1510, act: 34, gpa: 3.91 },
    programs: ["Медицина", "Инженерия", "Образование", "Музыка", "Бизнес"],
    competitiveness: 8,
    acceptanceRate: 6.7,
    description: "Престижный частный исследовательский университет на Юге",
    establishedYear: 1873,
    studentCount: 13796,
    internationalStudents: 1656,
  },
  {
    id: "rice",
    name: "Rice University",
    country: "США",
    city: "Хьюстон",
    ranking: 43,
    logo: "/placeholder-ujr47.png",
    website: "https://www.rice.edu",
    languages: ["Английский"],
    tuitionFee: { min: 54960, max: 54960, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 100, sat: 1520, act: 34, gpa: 4.12 },
    programs: ["Инженерия", "Естественные науки", "Бизнес", "Архитектура", "Музыка"],
    competitiveness: 9,
    acceptanceRate: 8.7,
    description: "Элитный частный исследовательский университет",
    establishedYear: 1912,
    studentCount: 7124,
    internationalStudents: 1425,
  },
  {
    id: "emory",
    name: "Emory University",
    country: "США",
    city: "Атланта",
    ranking: 44,
    logo: "/placeholder-ujr47.png",
    website: "https://www.emory.edu",
    languages: ["Английский"],
    tuitionFee: { min: 57948, max: 57948, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 100, sat: 1480, act: 33, gpa: 3.9 },
    programs: ["Медицина", "Бизнес", "Право", "Общественное здравоохранение", "Искусство"],
    competitiveness: 8,
    acceptanceRate: 13.0,
    description: "Престижный частный исследовательский университет",
    establishedYear: 1836,
    studentCount: 15440,
    internationalStudents: 3088,
  },
  {
    id: "georgetown",
    name: "Georgetown University",
    country: "США",
    city: "Вашингтон",
    ranking: 45,
    logo: "/placeholder-ujr47.png",
    website: "https://www.georgetown.edu",
    languages: ["Английский"],
    tuitionFee: { min: 62052, max: 62052, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 100, sat: 1480, act: 33, gpa: 4.01 },
    programs: ["Международные отношения", "Бизнес", "Право", "Медицина", "Политические науки"],
    competitiveness: 8,
    acceptanceRate: 12.2,
    description: "Престижный католический исследовательский университет",
    establishedYear: 1789,
    studentCount: 20935,
    internationalStudents: 3349,
  },
  {
    id: "notre-dame",
    name: "University of Notre Dame",
    country: "США",
    city: "Нотр-Дам",
    ranking: 46,
    logo: "/placeholder-ujr47.png",
    website: "https://www.nd.edu",
    languages: ["Английский"],
    tuitionFee: { min: 59794, max: 59794, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 100, sat: 1475, act: 33, gpa: 4.06 },
    programs: ["Бизнес", "Инженерия", "Архитектура", "Искусство", "Науки"],
    competitiveness: 8,
    acceptanceRate: 15.0,
    description: "Престижный католический исследовательский университет",
    establishedYear: 1842,
    studentCount: 12809,
    internationalStudents: 1281,
  },
  {
    id: "wake-forest",
    name: "Wake Forest University",
    country: "США",
    city: "Уинстон-Сейлем",
    ranking: 47,
    logo: "/placeholder-ujr47.png",
    website: "https://www.wfu.edu",
    languages: ["Английский"],
    tuitionFee: { min: 60876, max: 60876, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 100, sat: 1430, act: 32, gpa: 3.74 },
    programs: ["Бизнес", "Медицина", "Право", "Искусство", "Науки"],
    competitiveness: 7,
    acceptanceRate: 22.0,
    description: "Престижный частный исследовательский университет",
    establishedYear: 1834,
    studentCount: 8789,
    internationalStudents: 527,
  },
  {
    id: "tufts",
    name: "Tufts University",
    country: "США",
    city: "Медфорд",
    ranking: 48,
    logo: "/placeholder-ujr47.png",
    website: "https://www.tufts.edu",
    languages: ["Английский"],
    tuitionFee: { min: 63804, max: 63804, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 100, sat: 1490, act: 34, gpa: 4.04 },
    programs: ["Международные отношения", "Инженерия", "Медицина", "Искусство", "Науки"],
    competitiveness: 8,
    acceptanceRate: 9.7,
    description: "Престижный частный исследовательский университет",
    establishedYear: 1852,
    studentCount: 12326,
    internationalStudents: 1479,
  },
  {
    id: "nyu",
    name: "New York University",
    country: "США",
    city: "Нью-Йорк",
    ranking: 49,
    logo: "/placeholder-ujr47.png",
    website: "https://www.nyu.edu",
    languages: ["Английский"],
    tuitionFee: { min: 58168, max: 58168, currency: "USD" },
    requirements: { ielts: 7.5, toefl: 100, sat: 1470, act: 33, gpa: 3.7 },
    programs: ["Бизнес", "Искусство", "Право", "Медицина", "Инженерия"],
    competitiveness: 7,
    acceptanceRate: 12.8,
    description: "Крупный частный исследовательский университет в центре Нью-Йорка",
    establishedYear: 1831,
    studentCount: 59144,
    internationalStudents: 17326,
  },
  {
    id: "boston-university",
    name: "Boston University",
    country: "США",
    city: "Бостон",
    ranking: 50,
    logo: "/placeholder-ujr47.png",
    website: "https://www.bu.edu",
    languages: ["Английский"],
    tuitionFee: { min: 61050, max: 61050, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 90, sat: 1442, act: 33, gpa: 3.71 },
    programs: ["Коммуникации", "Бизнес", "Инженерия", "Медицина", "Искусство"],
    competitiveness: 7,
    acceptanceRate: 14.0,
    description: "Крупный частный исследовательский университет",
    establishedYear: 1839,
    studentCount: 37217,
    internationalStudents: 8929,
  },
  {
    id: "case-western",
    name: "Case Western Reserve University",
    country: "США",
    city: "Кливленд",
    ranking: 51,
    logo: "/placeholder-ujr47.png",
    website: "https://www.case.edu",
    languages: ["Английский"],
    tuitionFee: { min: 58109, max: 58109, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 90, sat: 1470, act: 33, gpa: 3.7 },
    programs: ["Инженерия", "Медицина", "Бизнес", "Право", "Искусство"],
    competitiveness: 7,
    acceptanceRate: 27.0,
    description: "Престижный частный исследовательский университет",
    establishedYear: 1826,
    studentCount: 12393,
    internationalStudents: 2478,
  },
  {
    id: "rochester",
    name: "University of Rochester",
    country: "США",
    city: "Рочестер",
    ranking: 52,
    logo: "/placeholder-ujr47.png",
    website: "https://www.rochester.edu",
    languages: ["Английский"],
    tuitionFee: { min: 61598, max: 61598, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 100, sat: 1480, act: 33, gpa: 3.8 },
    programs: ["Медицина", "Инженерия", "Бизнес", "Музыка", "Оптика"],
    competitiveness: 7,
    acceptanceRate: 30.0,
    description: "Исследовательский университет с сильными программами",
    establishedYear: 1850,
    studentCount: 12086,
    internationalStudents: 2900,
  },
  {
    id: "brandeis",
    name: "Brandeis University",
    country: "США",
    city: "Уолтем",
    ranking: 53,
    logo: "/placeholder-ujr47.png",
    website: "https://www.brandeis.edu",
    languages: ["Английский"],
    tuitionFee: { min: 61816, max: 61816, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 100, sat: 1450, act: 32, gpa: 3.9 },
    programs: ["Искусство", "Науки", "Бизнес", "Международные отношения", "Социальная политика"],
    competitiveness: 7,
    acceptanceRate: 31.0,
    description: "Престижный частный исследовательский университет",
    establishedYear: 1948,
    studentCount: 5825,
    internationalStudents: 1165,
  },
  {
    id: "tulane",
    name: "Tulane University",
    country: "США",
    city: "Новый Орлеан",
    ranking: 54,
    logo: "/placeholder-ujr47.png",
    website: "https://tulane.edu",
    languages: ["Английский"],
    tuitionFee: { min: 61834, max: 61834, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 90, sat: 1420, act: 32, gpa: 3.6 },
    programs: ["Бизнес", "Медицина", "Право", "Архитектура", "Общественное здравоохранение"],
    competitiveness: 7,
    acceptanceRate: 11.0,
    description: "Престижный частный исследовательский университет",
    establishedYear: 1834,
    studentCount: 14017,
    internationalStudents: 1402,
  },
  {
    id: "lehigh",
    name: "Lehigh University",
    country: "США",
    city: "Бетлехем",
    ranking: 55,
    logo: "/placeholder-ujr47.png",
    website: "https://www1.lehigh.edu",
    languages: ["Английский"],
    tuitionFee: { min: 59930, max: 59930, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 90, sat: 1420, act: 32, gpa: 3.7 },
    programs: ["Инженерия", "Бизнес", "Искусство", "Образование", "Здравоохранение"],
    competitiveness: 7,
    acceptanceRate: 32.0,
    description: "Престижный частный исследовательский университет",
    establishedYear: 1865,
    studentCount: 7208,
    internationalStudents: 1441,
  },
  {
    id: "northeastern",
    name: "Northeastern University",
    country: "США",
    city: "Бостон",
    ranking: 56,
    logo: "/placeholder-ujr47.png",
    website: "https://www.northeastern.edu",
    languages: ["Английский"],
    tuitionFee: { min: 59100, max: 59100, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 92, sat: 1465, act: 33, gpa: 4.04 },
    programs: ["Инженерия", "Бизнес", "Компьютерные науки", "Здравоохранение", "Искусство"],
    competitiveness: 7,
    acceptanceRate: 18.0,
    description: "Инновационный исследовательский университет с кооперативным образованием",
    establishedYear: 1898,
    studentCount: 27000,
    internationalStudents: 12000,
  },
  {
    id: "rensselaer",
    name: "Rensselaer Polytechnic Institute",
    country: "США",
    city: "Трой",
    ranking: 57,
    logo: "/placeholder-ujr47.png",
    website: "https://www.rpi.edu",
    languages: ["Английский"],
    tuitionFee: { min: 58600, max: 58600, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 88, sat: 1480, act: 33, gpa: 3.9 },
    programs: ["Инженерия", "Компьютерные науки", "Архитектура", "Бизнес", "Науки"],
    competitiveness: 8,
    acceptanceRate: 43.0,
    description: "Старейший технологический исследовательский университет",
    establishedYear: 1824,
    studentCount: 7000,
    internationalStudents: 1400,
  },
  {
    id: "villanova",
    name: "Villanova University",
    country: "США",
    city: "Вилланова",
    ranking: 58,
    logo: "/placeholder-ujr47.png",
    website: "https://www1.villanova.edu",
    languages: ["Английский"],
    tuitionFee: { min: 60768, max: 60768, currency: "USD" },
    requirements: { ielts: 7.0, toefl: 90, sat: 1470, act: 33, gpa: 3.9 },
    programs: ["Бизнес", "Инженерия", "Искусство", "Право", "Сестринское дело"],
    competitiveness: 7,
    acceptanceRate: 25.0,
    description: "Престижный католический исследовательский университет",
    establishedYear: 1842,
    studentCount: 11000,
    internationalStudents: 880,
  },
  {
    id: "pepperdine",
    name: "Pepperdine University",
    country: "США",
    city: "Малибу",
    ranking: 59,
    logo: "/placeholder-ujr47.png",
    website: "https://www.pepperdine.edu",
    languages: ["Английский"],
    tuitionFee: { min: 62390, max: 62390, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 80, sat: 1340, act: 30, gpa: 3.7 },
    programs: ["Бизнес", "Право", "Образование", "Общественная политика", "Искусство"],
    competitiveness: 6,
    acceptanceRate: 32.0,
    description: "Частный христианский исследовательский университет",
    establishedYear: 1937,
    studentCount: 7961,
    internationalStudents: 1592,
  },
  {
    id: "syracuse",
    name: "Syracuse University",
    country: "США",
    city: "Сиракьюс",
    ranking: 60,
    logo: "/placeholder-ujr47.png",
    website: "https://www.syracuse.edu",
    languages: ["Английский"],
    tuitionFee: { min: 58440, max: 58440, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 80, sat: 1380, act: 31, gpa: 3.7 },
    programs: ["Коммуникации", "Бизнес", "Инженерия", "Архитектура", "Искусство"],
    competitiveness: 6,
    acceptanceRate: 44.0,
    description: "Крупный частный исследовательский университет",
    establishedYear: 1870,
    studentCount: 22850,
    internationalStudents: 4570,
  },
  {
    id: "ubc",
    name: "University of British Columbia",
    country: "Канада",
    city: "Ванкувер",
    ranking: 61,
    logo: "/placeholder-ujr47.png",
    website: "https://www.ubc.ca",
    languages: ["Английский"],
    tuitionFee: { min: 28000, max: 45000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 90, gpa: 3.0 },
    programs: ["Медицина", "Инженерия", "Бизнес", "Искусство", "Науки"],
    competitiveness: 6,
    acceptanceRate: 52.0,
    description: "Ведущий исследовательский университет Канады",
    establishedYear: 1908,
    studentCount: 66000,
    internationalStudents: 17000,
  },
  {
    id: "waterloo",
    name: "University of Waterloo",
    country: "Канада",
    city: "Ватерлоо",
    ranking: 62,
    logo: "/placeholder-ujr47.png",
    website: "https://uwaterloo.ca",
    languages: ["Английский"],
    tuitionFee: { min: 25000, max: 40000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 90, gpa: 3.0 },
    programs: ["Инженерия", "Компьютерные науки", "Математика", "Бизнес", "Науки"],
    competitiveness: 7,
    acceptanceRate: 53.0,
    description: "Ведущий технологический университет Канады",
    establishedYear: 1957,
    studentCount: 42000,
    internationalStudents: 13000,
  },
  {
    id: "queens",
    name: "Queen's University",
    country: "Канада",
    city: "Кингстон",
    ranking: 63,
    logo: "/placeholder-ujr47.png",
    website: "https://www.queensu.ca",
    languages: ["Английский"],
    tuitionFee: { min: 22000, max: 35000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 88, gpa: 3.7 },
    programs: ["Бизнес", "Инженерия", "Медицина", "Право", "Искусство"],
    competitiveness: 7,
    acceptanceRate: 40.0,
    description: "Престижный канадский исследовательский университет",
    establishedYear: 1841,
    studentCount: 28000,
    internationalStudents: 3000,
  },
  {
    id: "mcmaster",
    name: "McMaster University",
    country: "Канада",
    city: "Гамильтон",
    ranking: 64,
    logo: "/placeholder-ujr47.png",
    website: "https://www.mcmaster.ca",
    languages: ["Английский"],
    tuitionFee: { min: 20000, max: 35000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 86, gpa: 3.0 },
    programs: ["Медицина", "Инженерия", "Бизнес", "Науки", "Социальные науки"],
    competitiveness: 6,
    acceptanceRate: 58.0,
    description: "Исследовательский университет с сильными программами",
    establishedYear: 1887,
    studentCount: 31000,
    internationalStudents: 4500,
  },
  {
    id: "alberta",
    name: "University of Alberta",
    country: "Канада",
    city: "Эдмонтон",
    ranking: 65,
    logo: "/placeholder-ujr47.png",
    website: "https://www.ualberta.ca",
    languages: ["Английский"],
    tuitionFee: { min: 18000, max: 30000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 86, gpa: 3.0 },
    programs: ["Инженерия", "Медицина", "Бизнес", "Искусство", "Науки"],
    competitiveness: 6,
    acceptanceRate: 58.0,
    description: "Крупный исследовательский университет Канады",
    establishedYear: 1908,
    studentCount: 40000,
    internationalStudents: 7000,
  },
  {
    id: "monash",
    name: "Monash University",
    country: "Австралия",
    city: "Мельбурн",
    ranking: 66,
    logo: "/placeholder-ujr47.png",
    website: "https://www.monash.edu",
    languages: ["Английский"],
    tuitionFee: { min: 30000, max: 50000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 79, gpa: 3.0 },
    programs: ["Медицина", "Инженерия", "Бизнес", "Искусство", "Право"],
    competitiveness: 6,
    acceptanceRate: 40.0,
    description: "Крупный исследовательский университет Австралии",
    establishedYear: 1958,
    studentCount: 80000,
    internationalStudents: 25000,
  },
  {
    id: "queensland",
    name: "University of Queensland",
    country: "Австралия",
    city: "Брисбен",
    ranking: 67,
    logo: "/placeholder-ujr47.png",
    website: "https://www.uq.edu.au",
    languages: ["Английский"],
    tuitionFee: { min: 32000, max: 48000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 87, gpa: 3.0 },
    programs: ["Медицина", "Инженерия", "Бизнес", "Науки", "Искусство"],
    competitiveness: 6,
    acceptanceRate: 63.0,
    description: "Ведущий исследовательский университет Австралии",
    establishedYear: 1909,
    studentCount: 54000,
    internationalStudents: 19000,
  },
  {
    id: "adelaide",
    name: "University of Adelaide",
    country: "Австралия",
    city: "Аделаида",
    ranking: 68,
    logo: "/placeholder-ujr47.png",
    website: "https://www.adelaide.edu.au",
    languages: ["Английский"],
    tuitionFee: { min: 30000, max: 45000, currency: "USD" },
    requirements: { ielts: 6.0, toefl: 79, gpa: 3.0 },
    programs: ["Медицина", "Инженерия", "Искусство", "Науки", "Бизнес"],
    competitiveness: 5,
    acceptanceRate: 73.0,
    description: "Исторический исследовательский университет Австралии",
    establishedYear: 1874,
    studentCount: 27000,
    internationalStudents: 9000,
  },
  {
    id: "western-australia",
    name: "University of Western Australia",
    country: "Австралия",
    city: "Перт",
    ranking: 69,
    logo: "/placeholder-ujr47.png",
    website: "https://www.uwa.edu.au",
    languages: ["Английский"],
    tuitionFee: { min: 28000, max: 42000, currency: "USD" },
    requirements: { ielts: 6.5, toefl: 82, gpa: 3.0 },
    programs: ["Медицина", "Инженерия", "Бизнес", "Искусство", "Науки"],
    competitiveness: 5,
    acceptanceRate: 70.0,
    description: "Престижный исследовательский университет Западной Австралии",
    establishedYear: 1911,
    studentCount: 25000,
    internationalStudents: 6000,
  },
  {
    id: "tu-munich",
    name: "Technical University of Munich",
    country: "Германия",
    city: "Мюнхен",
    ranking: 70,
    logo: "/placeholder-ujr47.png",
    website: "https://www.tum.de",
    languages: ["Немецкий", "Английский"],
    tuitionFee: { min: 0, max: 3000, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 88, gpa: 2.5 },
    programs: ["Инженерия", "Компьютерные науки", "Естественные науки", "Медицина", "Экономика"],
    competitiveness: 7,
    acceptanceRate: 8.0,
    description: "Ведущий технический университет Германии",
    establishedYear: 1868,
    studentCount: 45000,
    internationalStudents: 11000,
  },
  {
    id: "lmu-munich",
    name: "Ludwig Maximilian University of Munich",
    country: "Германия",
    city: "Мюнхен",
    ranking: 71,
    logo: "/placeholder-ujr47.png",
    website: "https://www.lmu.de",
    languages: ["Немецкий", "Английский"],
    tuitionFee: { min: 0, max: 3000, currency: "EUR" },
    requirements: { ielts: 6.0, toefl: 80, gpa: 2.5 },
    programs: ["Медицина", "Право", "Гуманитарные науки", "Естественные науки", "Экономика"],
    competitiveness: 6,
    acceptanceRate: 15.0,
    description: "Один из старейших университетов Германии",
    establishedYear: 1472,
    studentCount: 52000,
    internationalStudents: 8000,
  },
  {
    id: "heidelberg",
    name: "Heidelberg University",
    country: "Германия",
    city: "Гейдельберг",
    ranking: 72,
    logo: "/placeholder-ujr47.png",
    website: "https://www.uni-heidelberg.de",
    languages: ["Немецкий", "Английский"],
    tuitionFee: { min: 0, max: 3000, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 80, gpa: 2.5 },
    programs: ["Медицина", "Естественные науки", "Гуманитарные науки", "Право", "Экономика"],
    competitiveness: 6,
    acceptanceRate: 18.0,
    description: "Старейший университет Германии",
    establishedYear: 1386,
    studentCount: 30000,
    internationalStudents: 5000,
  },
  {
    id: "rwth-aachen",
    name: "RWTH Aachen University",
    country: "Германия",
    city: "Ахен",
    ranking: 73,
    logo: "/placeholder-ujr47.png",
    website: "https://www.rwth-aachen.de",
    languages: ["Немецкий", "Английский"],
    tuitionFee: { min: 0, max: 3000, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 90, gpa: 2.5 },
    programs: ["Инженерия", "Естественные науки", "Медицина", "Экономика", "Архитектура"],
    competitiveness: 7,
    acceptanceRate: 10.0,
    description: "Ведущий технический университет Европы",
    establishedYear: 1870,
    studentCount: 47000,
    internationalStudents: 11000,
  },
  {
    id: "kit",
    name: "Karlsruhe Institute of Technology",
    country: "Германия",
    city: "Карлсруэ",
    ranking: 74,
    logo: "/placeholder-ujr47.png",
    website: "https://www.kit.edu",
    languages: ["Немецкий", "Английский"],
    tuitionFee: { min: 0, max: 3000, currency: "EUR" },
    requirements: { ielts: 6.0, toefl: 88, gpa: 2.5 },
    programs: ["Инженерия", "Компьютерные науки", "Естественные науки", "Экономика", "Архитектура"],
    competitiveness: 6,
    acceptanceRate: 25.0,
    description: "Исследовательский университет с фокусом на технологии",
    establishedYear: 2009,
    studentCount: 25000,
    internationalStudents: 6000,
  },
  {
    id: "sorbonne",
    name: "Sorbonne University",
    country: "Франция",
    city: "Париж",
    ranking: 75,
    logo: "/placeholder-ujr47.png",
    website: "https://www.sorbonne-universite.fr",
    languages: ["Французский", "Английский"],
    tuitionFee: { min: 170, max: 3770, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 90, gpa: 3.0 },
    programs: ["Гуманитарные науки", "Естественные науки", "Медицина", "Инженерия", "Искусство"],
    competitiveness: 6,
    acceptanceRate: 30.0,
    description: "Престижный французский университет с богатой историей",
    establishedYear: 1150,
    studentCount: 55000,
    internationalStudents: 10000,
  },
  {
    id: "ecole-polytechnique",
    name: "École Polytechnique",
    country: "Франция",
    city: "Палезо",
    ranking: 76,
    logo: "/placeholder-ujr47.png",
    website: "https://www.polytechnique.edu",
    languages: ["Французский", "Английский"],
    tuitionFee: { min: 0, max: 12000, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 91, gpa: 3.5 },
    programs: ["Инженерия", "Математика", "Физика", "Экономика", "Компьютерные науки"],
    competitiveness: 9,
    acceptanceRate: 8.0,
    description: "Элитная французская инженерная школа",
    establishedYear: 1794,
    studentCount: 3000,
    internationalStudents: 1200,
  },
  {
    id: "ens-paris",
    name: "École Normale Supérieure",
    country: "Франция",
    city: "Париж",
    ranking: 77,
    logo: "/placeholder-ujr47.png",
    website: "https://www.ens.psl.eu",
    languages: ["Французский", "Английский"],
    tuitionFee: { min: 0, max: 3770, currency: "EUR" },
    requirements: { ielts: 7.0, toefl: 100, gpa: 3.8 },
    programs: ["Математика", "Физика", "Философия", "Литература", "Биология"],
    competitiveness: 10,
    acceptanceRate: 5.0,
    description: "Элитная французская школа для подготовки исследователей",
    establishedYear: 1794,
    studentCount: 2400,
    internationalStudents: 600,
  },
  {
    id: "epfl",
    name: "École Polytechnique Fédérale de Lausanne",
    country: "Швейцария",
    city: "Лозанна",
    ranking: 78,
    logo: "/placeholder-ujr47.png",
    website: "https://www.epfl.ch",
    languages: ["Французский", "Английский"],
    tuitionFee: { min: 1266, max: 1266, currency: "CHF" },
    requirements: { ielts: 7.0, toefl: 95, gpa: 3.5 },
    programs: ["Инженерия", "Компьютерные науки", "Естественные науки", "Архитектура", "Математика"],
    competitiveness: 8,
    acceptanceRate: 30.0,
    description: "Ведущий технологический университет Швейцарии",
    establishedYear: 1969,
    studentCount: 11000,
    internationalStudents: 6000,
  },
  {
    id: "university-zurich",
    name: "University of Zurich",
    country: "Швейцария",
    city: "Цюрих",
    ranking: 79,
    logo: "/placeholder-ujr47.png",
    website: "https://www.uzh.ch",
    languages: ["Немецкий", "Английский"],
    tuitionFee: { min: 1298, max: 1298, currency: "CHF" },
    requirements: { ielts: 7.0, toefl: 100, gpa: 3.0 },
    programs: ["Медицина", "Экономика", "Право", "Естественные науки", "Гуманитарные науки"],
    competitiveness: 6,
    acceptanceRate: 19.0,
    description: "Крупнейший университет Швейцарии",
    establishedYear: 1833,
    studentCount: 26000,
    internationalStudents: 5000,
  },
  {
    id: "university-geneva",
    name: "University of Geneva",
    country: "Швейцария",
    city: "Женева",
    ranking: 80,
    logo: "/placeholder-ujr47.png",
    website: "https://www.unige.ch",
    languages: ["Французский", "Английский"],
    tuitionFee: { min: 1000, max: 1000, currency: "CHF" },
    requirements: { ielts: 7.0, toefl: 100, gpa: 3.0 },
    programs: ["Международные отношения", "Медицина", "Право", "Экономика", "Естественные науки"],
    competitiveness: 6,
    acceptanceRate: 35.0,
    description: "Международный университет в сердце Европы",
    establishedYear: 1559,
    studentCount: 17000,
    internationalStudents: 6000,
  },
  {
    id: "amsterdam",
    name: "University of Amsterdam",
    country: "Нидерланды",
    city: "Амстердам",
    ranking: 81,
    logo: "/placeholder-ujr47.png",
    website: "https://www.uva.nl",
    languages: ["Нидерландский", "Английский"],
    tuitionFee: { min: 2314, max: 18750, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 92, gpa: 3.0 },
    programs: ["Экономика", "Психология", "Медицина", "Право", "Искусство"],
    competitiveness: 6,
    acceptanceRate: 25.0,
    description: "Ведущий исследовательский университет Нидерландов",
    establishedYear: 1632,
    studentCount: 42000,
    internationalStudents: 7000,
  },
  {
    id: "leiden",
    name: "Leiden University",
    country: "Нидерланды",
    city: "Лейден",
    ranking: 82,
    logo: "/placeholder-ujr47.png",
    website: "https://www.universiteitleiden.nl",
    languages: ["Нидерландский", "Английский"],
    tuitionFee: { min: 2314, max: 18750, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 90, gpa: 3.0 },
    programs: ["Право", "Медицина", "Гуманитарные науки", "Социальные науки", "Естественные науки"],
    competitiveness: 6,
    acceptanceRate: 40.0,
    description: "Старейший университет Нидерландов",
    establishedYear: 1575,
    studentCount: 27000,
    internationalStudents: 4000,
  },
  {
    id: "utrecht",
    name: "Utrecht University",
    country: "Нидерланды",
    city: "Утрехт",
    ranking: 83,
    logo: "/placeholder-ujr47.png",
    website: "https://www.uu.nl",
    languages: ["Нидерландский", "Английский"],
    tuitionFee: { min: 2314, max: 18750, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 93, gpa: 3.0 },
    programs: ["Ветеринария", "Медицина", "Естественные науки", "Гуманитарные науки", "Социальные науки"],
    competitiveness: 6,
    acceptanceRate: 22.0,
    description: "Престижный исследовательский университет",
    establishedYear: 1636,
    studentCount: 32000,
    internationalStudents: 7000,
  },
  {
    id: "erasmus",
    name: "Erasmus University Rotterdam",
    country: "Нидерланды",
    city: "Роттердам",
    ranking: 84,
    logo: "/placeholder-ujr47.png",
    website: "https://www.eur.nl",
    languages: ["Нидерландский", "Английский"],
    tuitionFee: { min: 2314, max: 18750, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 90, gpa: 3.0 },
    programs: ["Экономика", "Бизнес", "Медицина", "Право", "Социальные науки"],
    competitiveness: 6,
    acceptanceRate: 53.0,
    description: "Международный исследовательский университет",
    establishedYear: 1913,
    studentCount: 32000,
    internationalStudents: 5000,
  },
  {
    id: "kth",
    name: "KTH Royal Institute of Technology",
    country: "Швеция",
    city: "Стокгольм",
    ranking: 85,
    logo: "/placeholder-ujr47.png",
    website: "https://www.kth.se",
    languages: ["Шведский", "Английский"],
    tuitionFee: { min: 0, max: 18500, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 90, gpa: 3.0 },
    programs: ["Инженерия", "Архитектура", "Компьютерные науки", "Естественные науки", "Промышленная экономика"],
    competitiveness: 6,
    acceptanceRate: 35.0,
    description: "Ведущий технический университет Скандинавии",
    establishedYear: 1827,
    studentCount: 18000,
    internationalStudents: 3000,
  },
  {
    id: "karolinska",
    name: "Karolinska Institute",
    country: "Швеция",
    city: "Стокгольм",
    ranking: 86,
    logo: "/placeholder-ujr47.png",
    website: "https://ki.se",
    languages: ["Шведский", "Английский"],
    tuitionFee: { min: 0, max: 18500, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 90, gpa: 3.5 },
    programs: ["Медицина", "Биомедицина", "Общественное здравоохранение", "Стоматология", "Фармация"],
    competitiveness: 8,
    acceptanceRate: 10.0,
    description: "Ведущий медицинский университет мира",
    establishedYear: 1810,
    studentCount: 6000,
    internationalStudents: 1500,
  },
  {
    id: "lund",
    name: "Lund University",
    country: "Швеция",
    city: "Лунд",
    ranking: 87,
    logo: "/placeholder-ujr47.png",
    website: "https://www.lu.se",
    languages: ["Шведский", "Английский"],
    tuitionFee: { min: 0, max: 18500, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 90, gpa: 3.0 },
    programs: ["Инженерия", "Медицина", "Естественные науки", "Социальные науки", "Гуманитарные науки"],
    competitiveness: 6,
    acceptanceRate: 25.0,
    description: "Престижный скандинавский исследовательский университет",
    establishedYear: 1666,
    studentCount: 42000,
    internationalStudents: 4000,
  },
  {
    id: "stockholm",
    name: "Stockholm University",
    country: "Швеция",
    city: "Стокгольм",
    ranking: 88,
    logo: "/placeholder-ujr47.png",
    website: "https://www.su.se",
    languages: ["Шведский", "Английский"],
    tuitionFee: { min: 0, max: 18500, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 90, gpa: 3.0 },
    programs: ["Естественные науки", "Гуманитарные науки", "Социальные науки", "Право", "Бизнес"],
    competitiveness: 5,
    acceptanceRate: 30.0,
    description: "Крупный государственный исследовательский университет",
    establishedYear: 1878,
    studentCount: 33000,
    internationalStudents: 2000,
  },
  {
    id: "copenhagen",
    name: "University of Copenhagen",
    country: "Дания",
    city: "Копенгаген",
    ranking: 89,
    logo: "/placeholder-ujr47.png",
    website: "https://www.ku.dk",
    languages: ["Датский", "Английский"],
    tuitionFee: { min: 0, max: 18500, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 83, gpa: 3.0 },
    programs: ["Медицина", "Естественные науки", "Гуманитарные науки", "Социальные науки", "Право"],
    competitiveness: 6,
    acceptanceRate: 35.0,
    description: "Старейший и крупнейший университет Дании",
    establishedYear: 1479,
    studentCount: 37000,
    internationalStudents: 3000,
  },
  {
    id: "dtu",
    name: "Technical University of Denmark",
    country: "Дания",
    city: "Люнгбю",
    ranking: 90,
    logo: "/placeholder-ujr47.png",
    website: "https://www.dtu.dk",
    languages: ["Датский", "Английский"],
    tuitionFee: { min: 0, max: 18500, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 88, gpa: 3.0 },
    programs: ["Инженерия", "Естественные науки", "Биотехнологии", "Информационные технологии", "Архитектура"],
    competitiveness: 6,
    acceptanceRate: 40.0,
    description: "Ведущий технический университет Дании",
    establishedYear: 1829,
    studentCount: 11000,
    internationalStudents: 2000,
  },
  {
    id: "oslo",
    name: "University of Oslo",
    country: "Норвегия",
    city: "Осло",
    ranking: 91,
    logo: "/placeholder-ujr47.png",
    website: "https://www.uio.no",
    languages: ["Норвежский", "Английский"],
    tuitionFee: { min: 0, max: 0, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 90, gpa: 3.0 },
    programs: ["Медицина", "Право", "Естественные науки", "Гуманитарные науки", "Социальные науки"],
    competitiveness: 6,
    acceptanceRate: 30.0,
    description: "Старейший и престижнейший университет Норвегии",
    establishedYear: 1811,
    studentCount: 28000,
    internationalStudents: 3000,
  },
  {
    id: "ntnu",
    name: "Norwegian University of Science and Technology",
    country: "Норвегия",
    city: "Тронхейм",
    ranking: 92,
    logo: "/placeholder-ujr47.png",
    website: "https://www.ntnu.edu",
    languages: ["Норвежский", "Английский"],
    tuitionFee: { min: 0, max: 0, currency: "EUR" },
    requirements: { ielts: 6.0, toefl: 80, gpa: 3.0 },
    programs: ["Инженерия", "Естественные науки", "Информационные технологии", "Архитектура", "Медицина"],
    competitiveness: 6,
    acceptanceRate: 40.0,
    description: "Ведущий технологический университет Норвегии",
    establishedYear: 1996,
    studentCount: 42000,
    internationalStudents: 2000,
  },
  {
    id: "bergen",
    name: "University of Bergen",
    country: "Норвегия",
    city: "Берген",
    ranking: 93,
    logo: "/placeholder-ujr47.png",
    website: "https://www.uib.no",
    languages: ["Норвежский", "Английский"],
    tuitionFee: { min: 0, max: 0, currency: "EUR" },
    requirements: { ielts: 6.0, toefl: 80, gpa: 3.0 },
    programs: ["Медицина", "Естественные науки", "Гуманитарные науки", "Социальные науки", "Психология"],
    competitiveness: 5,
    acceptanceRate: 45.0,
    description: "Международный исследовательский университет",
    establishedYear: 1946,
    studentCount: 17000,
    internationalStudents: 2000,
  },
  {
    id: "helsinki",
    name: "University of Helsinki",
    country: "Финляндия",
    city: "Хельсинки",
    ranking: 94,
    logo: "/placeholder-ujr47.png",
    website: "https://www.helsinki.fi",
    languages: ["Финский", "Английский"],
    tuitionFee: { min: 0, max: 18000, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 92, gpa: 3.0 },
    programs: ["Медицина", "Естественные науки", "Гуманитарные науки", "Социальные науки", "Право"],
    competitiveness: 6,
    acceptanceRate: 30.0,
    description: "Старейший и крупнейший университет Финляндии",
    establishedYear: 1640,
    studentCount: 32000,
    internationalStudents: 2000,
  },
  {
    id: "aalto",
    name: "Aalto University",
    country: "Финляндия",
    city: "Эспоо",
    ranking: 95,
    logo: "/placeholder-ujr47.png",
    website: "https://www.aalto.fi",
    languages: ["Финский", "Английский"],
    tuitionFee: { min: 0, max: 18000, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 92, gpa: 3.0 },
    programs: ["Инженерия", "Бизнес", "Искусство", "Дизайн", "Архитектура"],
    competitiveness: 6,
    acceptanceRate: 35.0,
    description: "Инновационный университет с фокусом на технологии и дизайн",
    establishedYear: 2010,
    studentCount: 20000,
    internationalStudents: 4000,
  },
  {
    id: "turku",
    name: "University of Turku",
    country: "Финляндия",
    city: "Турку",
    ranking: 96,
    logo: "/placeholder-ujr47.png",
    website: "https://www.utu.fi",
    languages: ["Финский", "Английский"],
    tuitionFee: { min: 0, max: 18000, currency: "EUR" },
    requirements: { ielts: 6.5, toefl: 92, gpa: 3.0 },
    programs: ["Медицина", "Естественные науки", "Гуманитарные науки", "Социальные науки", "Образование"],
    competitiveness: 5,
    acceptanceRate: 40.0,
    description: "Международный исследовательский университет",
    establishedYear: 1920,
    studentCount: 20000,
    internationalStudents: 2000,
  },
  {
    id: "kyoto",
    name: "Kyoto University",
    country: "Япония",
    city: "Киото",
    ranking: 97,
    logo: "/placeholder-ujr47.png",
    website: "https://www.kyoto-u.ac.jp",
    languages: ["Японский", "Английский"],
    tuitionFee: { min: 3360, max: 3360, currency: "USD" },
    requirements: { ielts: 6.0, toefl: 79, gpa: 3.0 },
    programs: ["Естественные науки", "Инженерия", "Медицина", "Гуманитарные науки", "Экономика"],
    competitiveness: 8,
    acceptanceRate: 5.0,
    description: "Второй старейший университет Японии",
    establishedYear: 1897,
    studentCount: 23000,
    internationalStudents: 2500,
  },
  {
    id: "osaka",
    name: "Osaka University",
    country: "Япония",
    city: "Осака",
    ranking: 98,
    logo: "/placeholder-ujr47.png",
    website: "https://www.osaka-u.ac.jp",
    languages: ["Японский", "Английский"],
    tuitionFee: { min: 3360, max: 3360, currency: "USD" },
    requirements: { ielts: 6.0, toefl: 79, gpa: 3.0 },
    programs: ["Медицина", "Инженерия", "Естественные науки", "Гуманитарные науки", "Экономика"],
    competitiveness: 7,
    acceptanceRate: 8.0,
    description: "Престижный национальный университет Японии",
    establishedYear: 1931,
    studentCount: 24000,
    internationalStudents: 2000,
  },
  {
    id: "tohoku",
    name: "Tohoku University",
    country: "Япония",
    city: "Сендай",
    ranking: 99,
    logo: "/placeholder-ujr47.png",
    website: "https://www.tohoku.ac.jp",
    languages: ["Японский", "Английский"],
    tuitionFee: { min: 3360, max: 3360, currency: "USD" },
    requirements: { ielts: 6.0, toefl: 79, gpa: 3.0 },
    programs: ["Естественные науки", "Инженерия", "Медицина", "Гуманитарные науки", "Экономика"],
    competitiveness: 7,
    acceptanceRate: 10.0,
    description: "Ведущий исследовательский университет Японии",
    establishedYear: 1907,
    studentCount: 18000,
    internationalStudents: 2200,
  },
  {
    id: "nagoya",
    name: "Nagoya University",
    country: "Япония",
    city: "Нагоя",
    ranking: 100,
    logo: "/placeholder-ujr47.png",
    website: "https://en.nagoya-u.ac.jp",
    languages: ["Японский", "Английский"],
    tuitionFee: { min: 3360, max: 3360, currency: "USD" },
    requirements: { ielts: 6.0, toefl: 79, gpa: 3.0 },
    programs: ["Естественные науки", "Инженерия", "Медицина", "Гуманитарные науки", "Экономика"],
    competitiveness: 7,
    acceptanceRate: 12.0,
    description: "Престижный национальный университет с сильными исследовательскими программами",
    establishedYear: 1939,
    studentCount: 16000,
    internationalStudents: 2000,
  },
]

export const countries = [
  "США",
  "Великобритания",
  "Канада",
  "Австралия",
  "Германия",
  "Франция",
  "Швейцария",
  "Нидерланды",
  "Швеция",
  "Дания",
  "Норвегия",
  "Финляндия",
  "Япония",
  "Южная Корея",
  "Сингапур",
  "Гонконг",
  "Новая Зеландия",
  "Китай",
]

export const programs = [
  "Инженерия",
  "Компьютерные науки",
  "Медицина",
  "Бизнес",
  "Право",
  "Естественные науки",
  "Математика",
  "Физика",
  "Химия",
  "Биология",
  "Экономика",
  "Психология",
  "Социальные науки",
  "Гуманитарные науки",
  "Искусство",
  "Архитектура",
  "Дизайн",
  "Журналистика",
  "Образование",
  "Политические науки",
  "Социология",
  "Международные отношения",
]

export const languages = [
  "Английский",
  "Немецкий",
  "Французский",
  "Испанский",
  "Итальянский",
  "Нидерландский",
  "Шведский",
  "Датский",
  "Норвежский",
  "Финский",
  "Китайский",
  "Японский",
]
